pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-p 8002:8002'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
		input message: 'Finished using the web site?'
		sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
